import Link from "next/link";
import {ArrowLeft, ArrowRight, ReceiptText} from "lucide-react";

import type {ShareTransaction} from "@/lib/go-api-client";
import {formatShareDate, formatShareMoney, ShareTransactionBadge} from "./share-badges";
import {ReverseTransactionDialog} from "./reverse-transaction-dialog";

// ShareTransactionList keeps audit details readable on mobile and exposes reversals only on original entries.
export function ShareTransactionList({accountId, transactions, page, previousHref, nextHref}: {accountId: string; transactions: ShareTransaction[]; page: number; previousHref?: string; nextHref?: string}) {
  return <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-stone-200 px-5 py-4 sm:px-6"><div><h2 className="font-semibold text-stone-950">Transaction history</h2><p className="mt-1 text-xs text-stone-500">Page {page} · Internal references and running balances from the share ledger.</p></div><ReceiptText className="size-5 text-stone-400" /></div>
    {transactions.length ? <><div className="hidden overflow-x-auto md:block"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-stone-50 text-xs uppercase tracking-wide text-stone-500"><tr><th className="px-6 py-3">Date</th><th className="px-6 py-3">Type</th><th className="px-6 py-3">Amount</th><th className="px-6 py-3">Balance after</th><th className="px-6 py-3">Internal reference / reason</th><th className="px-6 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-stone-100">{transactions.map((item) => <tr key={item.id}><td className="whitespace-nowrap px-6 py-4 text-stone-600">{formatShareDate(item.createdAt, true)}</td><td className="px-6 py-4"><ShareTransactionBadge type={item.type} /></td><td className="whitespace-nowrap px-6 py-4 font-semibold text-stone-950">{formatShareMoney(item.amount)}</td><td className="whitespace-nowrap px-6 py-4 text-stone-700">{formatShareMoney(item.balanceAfter)}</td><td className="max-w-xs px-6 py-4"><p className="break-all font-mono text-xs text-stone-700">{item.referenceId || "—"}</p><p className="mt-1 break-words text-xs text-stone-500">{item.reason || "No reason provided"}</p></td><td className="px-6 py-4">{item.type !== "SHARE_TRANSACTION_TYPE_REVERSAL" ? <ReverseTransactionDialog accountId={accountId} transactionId={item.id} /> : null}</td></tr>)}</tbody></table></div>
      <div className="divide-y divide-stone-100 md:hidden">{transactions.map((item) => <article className="p-5" key={item.id}><div className="flex items-start justify-between gap-3"><div><ShareTransactionBadge type={item.type} /><p className="mt-2 text-lg font-bold text-stone-950">{formatShareMoney(item.amount)}</p></div>{item.type !== "SHARE_TRANSACTION_TYPE_REVERSAL" ? <ReverseTransactionDialog accountId={accountId} transactionId={item.id} /> : null}</div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-stone-500">Balance after</dt><dd className="mt-1 font-semibold text-stone-800">{formatShareMoney(item.balanceAfter)}</dd></div><div><dt className="text-stone-500">Date</dt><dd className="mt-1 text-stone-800">{formatShareDate(item.createdAt, true)}</dd></div><div className="col-span-2"><dt className="text-stone-500">Internal reference</dt><dd className="mt-1 break-all font-mono text-stone-800">{item.referenceId || "—"}</dd></div><div className="col-span-2"><dt className="text-stone-500">Reason</dt><dd className="mt-1 break-words text-stone-800">{item.reason || "No reason provided"}</dd></div></dl></article>)}</div></> : <div className="px-6 py-14 text-center"><ReceiptText className="mx-auto size-9 text-stone-300" /><h3 className="mt-3 font-semibold text-stone-900">{page > 1 ? "No more transactions" : "No transactions yet"}</h3><p className="mt-1 text-sm text-stone-500">{page > 1 ? "Return to the previous page to continue browsing." : "Purchases, withdrawals, and adjustments will appear here."}</p></div>}
    {(previousHref || nextHref) ? <div className="flex items-center justify-between border-t border-stone-200 px-5 py-4"><span>{previousHref ? <Link className="inline-flex items-center gap-2 text-sm font-semibold text-stone-700" href={previousHref}><ArrowLeft className="size-4" />Previous</Link> : null}</span><span>{nextHref ? <Link className="inline-flex items-center gap-2 text-sm font-semibold text-[#a91521]" href={nextHref}>Next<ArrowRight className="size-4" /></Link> : null}</span></div> : null}</section>;
}
