"use client";

import {useActionState, useRef} from "react";
import {LoaderCircle, Wallet, X} from "lucide-react";

import {requestCreditWithdrawalAction} from "@/app/dashboard/loans/credit-actions";
import type {CreditBalance as Credit} from "@/lib/go-api-client";
import {LoanFeedback, LoanFieldError, loanInputClass, loanTextareaClass} from "./form-parts";
import {formatLoanDate, formatLoanMoney, LoanBadge} from "./loan-badges";

// CreditWithdrawalDialog confirms the amount and reason before creating a withdrawal request.
function CreditWithdrawalDialog({credit, loanId}: {credit: Credit; loanId: string}) { const dialog = useRef<HTMLDialogElement>(null); const [state, action, pending] = useActionState(requestCreditWithdrawalAction, null); return <><button className="h-9 rounded-lg bg-stone-900 px-3 text-sm font-semibold text-white" onClick={() => dialog.current?.showModal()} type="button">Request withdrawal</button><dialog className="m-auto w-[calc(100%-2rem)] max-w-md rounded-2xl border-0 p-0 shadow-2xl backdrop:bg-stone-950/35" ref={dialog}><div className="flex justify-between border-b p-5"><h2 className="font-semibold">Request credit withdrawal</h2><button onClick={() => dialog.current?.close()} type="button"><X className="size-4" /></button></div><form action={action} className="space-y-4 p-5"><input name="loanId" type="hidden" value={loanId} /><input name="creditBalanceId" type="hidden" value={credit.id} /><label className="block text-sm font-medium">Amount<input className={loanInputClass} inputMode="decimal" name="amount" required /></label><LoanFieldError name="amount" state={state} /><label className="block text-sm font-medium">Reason<textarea className={loanTextareaClass} name="reason" required /></label><LoanFeedback state={state} /><button className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#a91521] px-4 text-sm font-semibold text-white" disabled={pending} type="submit">{pending ? <LoaderCircle className="size-4 animate-spin" /> : <Wallet className="size-4" />}Submit request</button></form></dialog></>; }
// CreditBalance shows returned overpayment credit only when the backend reports it.
export function CreditBalance({credits, loanId}: {credits: Credit[]; loanId: string}) { if (!credits.length) return null; return <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="mb-4"><h2 className="font-semibold">Credit balances</h2><p className="mt-1 text-xs text-stone-500">Overpayments, refunds, and adjustments associated with this loan</p></div><div className="space-y-3">{credits.map((credit) => <div className="flex flex-col gap-3 rounded-xl border border-stone-200 p-4 sm:flex-row sm:items-center" key={credit.id}><div className="flex-1"><p className="text-lg font-bold">{formatLoanMoney(credit.amount)}</p><p className="mt-1 text-xs capitalize text-stone-500">{credit.source || "Credit"} · Updated {formatLoanDate(credit.lastActivityAt)}</p></div><LoanBadge status={credit.status} />{credit.status === "CREDIT_STATUS_AVAILABLE" ? <CreditWithdrawalDialog credit={credit} loanId={loanId} /> : null}</div>)}</div></section>; }
