import {AlertTriangle, Clock3, FilePlus2, WalletCards} from "lucide-react";

import type {Loan, LoanStatus} from "@/lib/go-api-client";
import {formatLoanMoney, loanLabel} from "./loan-badges";

const tracked: LoanStatus[] = ["LOAN_STATUS_PENDING", "LOAN_STATUS_MANUAL_REVIEW", "LOAN_STATUS_APPROVED", "LOAN_STATUS_ACTIVE", "LOAN_STATUS_DELINQUENT", "LOAN_STATUS_CLOSED"];

// LoanAnalytics summarizes only the loaded cursor page so it never presents partial data as branch totals.
export function LoanAnalytics({loans}: {loans: Loan[]}) {
  const principal = loans.reduce((sum, loan) => sum + Number(loan.principal || 0), 0);
  const months = Array.from(new Set(loans.map((loan) => loan.createdAt.slice(0, 7)))).sort().slice(-6);
  const monthly = months.map((month) => loans.filter((loan) => loan.createdAt.startsWith(month)).reduce((sum, loan) => sum + Number(loan.principal || 0), 0));
  const maximum = Math.max(...monthly, 1), statusMaximum = Math.max(...tracked.map((status) => loans.filter((loan) => loan.status === status).length), 1);
  const line = monthly.map((value, index) => `${monthly.length === 1 ? 50 : index * 100 / (monthly.length - 1)},${90 - value / maximum * 72}`).join(" ");
  const cards = [{label: "Loans on this page", value: String(loans.length), icon: FilePlus2}, {label: "Requested principal", value: formatLoanMoney(String(principal)), icon: WalletCards}, {label: "Pending review", value: String(loans.filter((loan) => loan.status === "LOAN_STATUS_PENDING" || loan.status === "LOAN_STATUS_MANUAL_REVIEW").length), icon: Clock3}, {label: "Delinquent", value: String(loans.filter((loan) => loan.status === "LOAN_STATUS_DELINQUENT").length), icon: AlertTriangle}];
  return <section className="space-y-4"><div className="flex items-end justify-between"><div><h2 className="font-semibold text-stone-950">Current page snapshot</h2><p className="mt-1 text-xs text-stone-500">These figures describe only the loans loaded below.</p></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({label, value, icon: Icon}) => <div className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm" key={label}><div className="flex items-center justify-between"><p className="text-xs font-medium text-stone-500">{label}</p><Icon className="size-4 text-[#a91521]" /></div><p className="mt-3 break-words text-xl font-bold">{value}</p></div>)}</div><div className="grid gap-4 xl:grid-cols-2"><div className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold">Application principal</h3><p className="mt-1 text-xs text-stone-500">Monthly totals represented on this page</p>{monthly.length ? <><svg className="mt-5 h-40 w-full" preserveAspectRatio="none" viewBox="0 0 100 100"><polyline fill="none" points={line} stroke="#a91521" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" vectorEffect="non-scaling-stroke" />{monthly.map((value, index) => <circle cx={monthly.length === 1 ? 50 : index * 100 / (monthly.length - 1)} cy={90 - value / maximum * 72} fill="#a91521" key={months[index]} r="1.8" vectorEffect="non-scaling-stroke" />)}</svg><div className="flex justify-between text-xs text-stone-400">{months.map((month) => <span key={month}>{month}</span>)}</div></> : <div className="grid h-44 place-items-center text-sm text-stone-500">No application data on this page.</div>}</div><div className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold">Loan status</h3><p className="mt-1 text-xs text-stone-500">Counts represented on this page</p><div className="mt-5 space-y-3">{tracked.map((status) => { const count = loans.filter((loan) => loan.status === status).length; return <div key={status}><div className="mb-1 flex justify-between text-xs"><span>{loanLabel(status)}</span><strong>{count}</strong></div><div className="h-2 rounded-full bg-stone-100"><div className="h-2 rounded-full bg-[#a91521]" style={{width: `${count / statusMaximum * 100}%`}} /></div></div>; })}</div></div></div></section>;
}
