import Link from "next/link";
import {ArrowLeft, ArrowRight, ChevronRight, FileText} from "lucide-react";

import type {Loan} from "@/lib/go-api-client";
import {formatLoanDate, formatLoanMoney, LoanBadge} from "./loan-badges";

// LoanList makes every directory row actionable and keeps the same facts readable on mobile.
export function LoanList({loans, page, previousHref, nextHref}: {loans: Loan[]; page: number; previousHref?: string; nextHref?: string}) {
  return <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-stone-200 px-5 py-4 sm:px-6"><div><h2 className="font-semibold text-stone-950">Loan directory</h2><p className="mt-1 text-xs text-stone-500">Page {page} · Select a loan to open its workspace.</p></div><FileText className="size-5 text-stone-400" /></div>
    {loans.length ? <><div className="hidden overflow-x-auto md:block"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-stone-50 text-xs uppercase tracking-wide text-stone-500"><tr><th className="px-6 py-3">Member</th><th className="px-6 py-3">Principal</th><th className="px-6 py-3">Rate and term</th><th className="px-6 py-3">Status</th><th className="px-6 py-3">Applied</th><th className="px-6 py-3">Updated</th><th className="w-10 px-6 py-3"><span className="sr-only">Open</span></th></tr></thead><tbody className="divide-y divide-stone-100">{loans.map((loan) => <tr className="group hover:bg-red-50/45" key={loan.id}><td className="p-0" colSpan={7}><Link className="grid grid-cols-[minmax(11rem,1.2fr)_minmax(8rem,.8fr)_minmax(9rem,.8fr)_minmax(8rem,.8fr)_minmax(8rem,.8fr)_minmax(8rem,.8fr)_2rem] items-center px-6 py-4" href={`/dashboard/loans/${loan.id}`} prefetch={false}><span className="min-w-0"><strong className="block break-words text-stone-900">{loan.memberName || "Member"}</strong><small className="mt-1 block break-all text-stone-500">{loan.memberNumber || loan.memberId}</small></span><strong>{formatLoanMoney(loan.principal)}</strong><span className="text-stone-600">{loan.interestRate}% · {loan.repaymentPeriodMonths} months</span><span><LoanBadge status={loan.status} /></span><span className="text-stone-600">{formatLoanDate(loan.createdAt)}</span><span className="text-stone-600">{formatLoanDate(loan.updatedAt)}</span><ChevronRight className="size-4 text-stone-400 group-hover:text-[#a91521]" /></Link></td></tr>)}</tbody></table></div>
      <div className="divide-y divide-stone-100 md:hidden">{loans.map((loan) => <Link className="flex items-center gap-3 p-5" href={`/dashboard/loans/${loan.id}`} key={loan.id} prefetch={false}><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h3 className="break-words font-semibold">{loan.memberName || "Member"}</h3><p className="break-all text-xs text-stone-500">{loan.memberNumber || loan.memberId}</p></div><LoanBadge status={loan.status} /></div><p className="mt-3 text-lg font-bold">{formatLoanMoney(loan.principal)}</p><p className="mt-1 text-xs text-stone-500">{loan.interestRate}% · {loan.repaymentPeriodMonths} months · Applied {formatLoanDate(loan.createdAt)}</p></div><ChevronRight className="size-4 shrink-0 text-stone-400" /></Link>)}</div></> : <div className="px-6 py-16 text-center"><FileText className="mx-auto size-9 text-stone-300" /><h3 className="mt-3 font-semibold">{page > 1 ? "No more loans" : "No loans found"}</h3><p className="mt-1 text-sm text-stone-500">{page > 1 ? "Return to the previous page to continue browsing." : "Try another filter or submit the first matching application."}</p></div>}
    {(previousHref || nextHref) ? <div className="flex justify-between border-t border-stone-200 px-5 py-4"><span>{previousHref ? <Link className="inline-flex items-center gap-2 text-sm font-semibold" href={previousHref}><ArrowLeft className="size-4" />Previous</Link> : null}</span><span>{nextHref ? <Link className="inline-flex items-center gap-2 text-sm font-semibold text-[#a91521]" href={nextHref}>Next<ArrowRight className="size-4" /></Link> : null}</span></div> : null}</section>;
}
