import Link from "next/link";
import {Landmark, Plus, Search} from "lucide-react";

import type {LoanStatus} from "@/lib/go-api-client";
import {loanLabel} from "./loan-badges";

const statuses: Array<"" | LoanStatus> = ["", "LOAN_STATUS_PENDING", "LOAN_STATUS_APPROVED", "LOAN_STATUS_REJECTED", "LOAN_STATUS_DISBURSED", "LOAN_STATUS_RESTRUCTURING", "LOAN_STATUS_ACTIVE", "LOAN_STATUS_DELINQUENT", "LOAN_STATUS_CLOSED", "LOAN_STATUS_WRITTEN_OFF", "LOAN_STATUS_MANUAL_REVIEW"];

// LoanDirectoryHeader groups the page identity, application entry point, search, and status filter.
export function LoanDirectoryHeader({lookup, lookupBy, status}: {lookup: string; lookupBy: string; status: string}) {
  return <><section className="rounded-2xl bg-linear-to-r from-[#961521] to-[#c8242f] px-6 py-7 text-white shadow-[0_16px_45px_rgba(153,27,39,0.16)] sm:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="mb-2 flex items-center gap-2 text-sm font-medium text-red-100"><Landmark className="size-4" />Branch 01 · Loan administration</p><h1 className="text-3xl font-bold tracking-tight">Loans</h1><p className="mt-2 text-sm text-red-50/85">Review applications, manage lending decisions, and track repayments.</p></div><Link className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-white px-5 text-sm font-semibold text-[#a91521]" href="/dashboard/loans/new"><Plus className="size-4" />Apply for loan</Link></div></section>
    <section className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto]"><form className="grid gap-3 sm:grid-cols-[10rem_minmax(0,1fr)_auto]" method="get"><select aria-label="Lookup field" className="h-11 rounded-xl border border-stone-200 bg-stone-50 px-3 text-sm" defaultValue={lookupBy} name="lookupBy"><option value="loanId">Loan ID</option><option value="memberId">Member ID</option></select><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-stone-400" /><input className="h-11 w-full rounded-xl border border-stone-200 bg-stone-50 pl-10 pr-3 text-sm outline-none focus:border-[#a91521]" defaultValue={lookup} name="lookup" placeholder={`Enter exact ${lookupBy === "memberId" ? "member" : "loan"} ID`} /></div><button className="h-11 rounded-lg bg-stone-900 px-5 text-sm font-semibold text-white" type="submit">Find loan</button></form><form className="flex gap-2" method="get"><select aria-label="Filter by status" className="h-11 min-w-44 flex-1 rounded-xl border border-stone-200 px-3 text-sm" defaultValue={status} name="status">{statuses.map((item) => <option key={item || "all"} value={item}>{item ? loanLabel(item) : "All statuses"}</option>)}</select><button className="h-11 rounded-lg border border-stone-200 px-4 text-sm font-semibold" type="submit">Apply</button></form></div></section></>;
}
