"use client";

import {useActionState, useState} from "react";
import Link from "next/link";
import {ArrowLeft, LoaderCircle, Plus, Send, Trash2} from "lucide-react";

import {applyForLoanAction} from "@/app/dashboard/loans/actions";
import {LoanFeedback, LoanFieldError, loanInputClass} from "./form-parts";

// LoanApplicationForm keeps all application terms visible in one reviewable form instead of a wizard.
export function LoanApplicationForm() {
  const [state, action, pending] = useActionState(applyForLoanAction, null);
  const [guarantors, setGuarantors] = useState(1);
  return <form action={action} className="space-y-6"><section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="font-semibold">Member and loan terms</h2><p className="mt-1 text-sm text-stone-500">Use the member ID currently accepted by the loan service.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Member ID<input className={loanInputClass} disabled={pending} name="memberId" required /></label><LoanFieldError name="memberId" state={state} /><label className="text-sm font-medium">Principal (KES)<input className={loanInputClass} disabled={pending} inputMode="decimal" name="principal" placeholder="0.00" required /></label><label className="text-sm font-medium">Interest rate (%)<input className={loanInputClass} disabled={pending} inputMode="decimal" name="interestRate" placeholder="0.00" required /></label><label className="text-sm font-medium">Repayment period (months)<input className={loanInputClass} disabled={pending} min="1" name="repaymentPeriodMonths" required type="number" /></label><label className="text-sm font-medium">Share pledge (KES)<input className={loanInputClass} disabled={pending} inputMode="decimal" name="sharePledge" placeholder="0.00" required /></label></div></section>
    <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">Proposed guarantors</h2><p className="mt-1 text-sm text-stone-500">Complete both fields for every guarantor used.</p></div><button className="inline-flex h-9 shrink-0 items-center gap-2 rounded-lg border border-stone-200 px-3 text-sm font-semibold" onClick={() => setGuarantors((count) => count + 1)} type="button"><Plus className="size-4" />Add</button></div><div className="mt-5 grid gap-5 lg:grid-cols-2">{Array.from({length: guarantors}, (_, index) => <fieldset className="grid gap-3 rounded-xl border border-stone-200 p-4" key={index}><legend className="px-2 text-sm font-semibold">Guarantor {index + 1}</legend><label className="text-sm font-medium">Member ID<input className={loanInputClass} disabled={pending} name="guarantorId" /></label><label className="text-sm font-medium">Guaranteed amount (KES)<input className={loanInputClass} disabled={pending} inputMode="decimal" name="guaranteedAmount" /></label>{guarantors > 1 && index === guarantors - 1 ? <button className="inline-flex items-center gap-2 text-sm font-semibold text-red-700" onClick={() => setGuarantors((count) => count - 1)} type="button"><Trash2 className="size-4" />Remove last row</button> : null}</fieldset>)}</div></section>
    <LoanFeedback state={state} /><div className="flex flex-col-reverse justify-between gap-3 sm:flex-row"><Link className="inline-flex h-11 items-center justify-center gap-2 rounded-lg border border-stone-200 bg-white px-5 text-sm font-semibold" href="/dashboard/loans"><ArrowLeft className="size-4" />Cancel</Link><button className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-[#a91521] px-5 text-sm font-semibold text-white disabled:opacity-50" disabled={pending} type="submit">{pending ? <LoaderCircle className="size-4 animate-spin" /> : <Send className="size-4" />}Submit application</button></div></form>;
}
