"use client";

import {useActionState, useRef} from "react";
import {Banknote, LoaderCircle, X} from "lucide-react";

import {recordRepaymentAction} from "@/app/dashboard/loans/repayment-actions";
import {LoanFeedback, LoanFieldError, loanInputClass} from "./form-parts";

// RecordRepaymentDialog captures only the amount and idempotent gateway reference required by the backend.
export function RecordRepaymentDialog({loanId}: {loanId: string}) { const dialog = useRef<HTMLDialogElement>(null); const [state, action, pending] = useActionState(recordRepaymentAction, null); return <><button className="inline-flex h-10 items-center gap-2 rounded-lg bg-white px-4 text-sm font-semibold text-[#a91521]" onClick={() => dialog.current?.showModal()} type="button"><Banknote className="size-4" />Record repayment</button><dialog className="m-auto w-[calc(100%-2rem)] max-w-lg rounded-2xl border-0 bg-white p-0 shadow-2xl backdrop:bg-stone-950/35" ref={dialog}><div className="flex justify-between border-b p-5"><div><h2 className="text-lg font-semibold">Record repayment</h2><p className="mt-1 text-sm text-stone-500">The backend will allocate this payment.</p></div><button aria-label="Close" onClick={() => dialog.current?.close()} type="button"><X className="size-4" /></button></div><form action={action} className="space-y-4 p-5"><input name="loanId" type="hidden" value={loanId} /><label className="block text-sm font-medium">Amount (KES)<input className={loanInputClass} disabled={pending} inputMode="decimal" name="amount" required /></label><LoanFieldError name="amount" state={state} /><label className="block text-sm font-medium">Gateway transaction ID<input className={loanInputClass} disabled={pending} name="paymentGatewayTransactionId" required /></label><LoanFieldError name="paymentGatewayTransactionId" state={state} /><LoanFeedback state={state} /><div className="flex justify-end gap-2"><button className="h-10 rounded-lg border px-4 text-sm font-semibold" onClick={() => dialog.current?.close()} type="button">Cancel</button><button className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#a91521] px-4 text-sm font-semibold text-white" disabled={pending} type="submit">{pending ? <LoaderCircle className="size-4 animate-spin" /> : <Banknote className="size-4" />}Record</button></div></form></dialog></>; }
